apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: taytelar-secrets-provider
  namespace: taytelar-ns
spec:
  provider: "aws" 
  secretObjects:
  - secretName: postgres-credentials
    type: Opaque
    data:
    - objectName: postgres-credentials
      key: SECRET_KEY 

  - secretName: razorpay-credentials
    type: Opaque
    data:
    - objectName: razorpay-credentials
      key: SECRET_KEY 

  - secretName: fast2sms-api
    type: Opaque
    data:
    - objectName: fast2sms-api
      key: SECRET_KEY

  - secretName: aws-credentials
    type: Opaque
    data:
    - objectName: aws-credentials
      key: SECRET_KEY 

  - secretName: aws-bucket
    type: Opaque
    data:
    - objectName: aws-bucket
      key: SECRET_KEY 

  parameters:
    objects: |
      array:
        - objectName: postgres-credentials
          objectType: "secrets"
        - objectName: razorpay-credentials
          objectType: "secrets"
        - objectName: fast2sms-api
          objectType: "secrets"
        - objectName: aws-credentials
          objectType: "secrets"
        - objectName: aws-bucket
          objectType: "secrets"
