apiVersion: v1
kind: ServiceAccount
metadata:
  name: taytelar-service-account
  namespace: taytelar-ns
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::794038231860:role/taytaler-password-access

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-store-csi-driver
  namespace: kube-system

  ---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-secrets-store-provider-aws
  namespace: kube-system

