apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-pv  # Name of the persistent volume
spec:
  capacity:
    storage: 1Gi  # Size of the volume
  accessModes:
    - ReadWriteOnce  # Access mode
  persistentVolumeReclaimPolicy: Delete  # Policy for reclaiming the PV
  storageClassName: gp2  # Should match your StorageClass
  hostPath:
    path: /data/backend  # Path on the node (for static provisioning)
